# Generated by Django 4.1.5 on 2023-04-03 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('address_line', models.CharField(default='', max_length=120)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=60)),
                ('province', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=80)),
                ('product_description', models.CharField(max_length=200)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_price', models.FloatField()),
                ('product_price_sale', models.FloatField(blank=True)),
                ('product_available', models.BooleanField()),
                ('product_weight', models.FloatField()),
                ('product_height', models.FloatField()),
                ('image', models.ImageField(upload_to='frontend/src/productimages')),
                ('type_foreign_key', models.ManyToManyField(blank=True, related_name='Types', to='api.types')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('products', models.CharField(blank=True, max_length=255)),
                ('order_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Carts', to='api.products')),
            ],
        ),
    ]
