# Generated by Django 4.1.3 on 2023-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
