# Generated by Django 4.1.3 on 2023-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerPhone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='streetNumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line',
            field=models.CharField(default='', max_length=120),
        ),
    ]
