# Generated by Django 4.1.3 on 2023-03-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerPhone',
            field=models.CharField(max_length=10),
        ),
    ]
