# Generated by Django 4.1.3 on 2023-03-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_customerphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_weight',
            field=models.FloatField(blank=True),
        ),
    ]
