# Generated by Django 4.1.5 on 2023-03-28 05:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_customerphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item_Orders',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orde_total',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='api.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_total',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Cart',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='frontend/src/productimages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price_sale',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='api.customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='api.products'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='api.customer'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='api.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_product',
            field=models.ManyToManyField(to='api.orderproduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Carts', to='api.products'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Cart',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='api.cart'),
        ),
    ]
