# Generated by Django 4.1.3 on 2023-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.IntegerField(default=1, max_length=17),
        ),
    ]
