# Generated by Django 4.1.3 on 2023-01-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customer_order_foreign_key_alter_customer_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Order_foreign_key',
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='Orders', to='api.orders'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(related_name='Cart', to='api.cart'),
        ),
    ]
