# Generated by Django 4.1.3 on 2023-01-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_customer_order_foreign_key_customer_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type_foreign_key',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='api.cart'),
        ),
    ]
