# Generated by Django 4.1.3 on 2023-01-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customer_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
    ]
