# Generated by Django 4.1.3 on 2023-02-01 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_products_type_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type_foreign_key',
        ),
        migrations.AddField(
            model_name='products',
            name='type_foreign_key',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.types'),
            preserve_default=False,
        ),
    ]
