# Generated by Django 4.1.3 on 2023-02-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_products_type_foreign_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type_foreign_key',
        ),
        migrations.AddField(
            model_name='products',
            name='type_foreign_key',
            field=models.ManyToManyField(blank=True, related_name='Types', to='api.types'),
        ),
    ]
