# Generated by Django 4.1.3 on 2023-02-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_products_type_foreign_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Cart',
            field=models.ManyToManyField(blank=True, related_name='Cart', to='api.cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='Orders', to='api.orders'),
        ),
    ]
