# Generated by Django 4.1.3 on 2023-02-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customer_cart_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products'),
        ),
    ]
