# Generated by Django 4.1.3 on 2023-02-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_orders_item_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_height',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_price_sale',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_weight',
        ),
        migrations.RemoveField(
            model_name='products',
            name='type_foreign_key',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
