# Generated by Django 4.1.3 on 2023-02-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_products_content_remove_products_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_height',
            field=models.FloatField(),
        ),
    ]
