# Generated by Django 4.1.3 on 2023-02-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_available',
            field=models.BooleanField(default=True),
        ),
    ]
