# Generated by Django 4.1.3 on 2023-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_products_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_expire_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.IntegerField(blank=True, default=1, max_length=17),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cvc_number',
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
