# Generated by Django 4.1.3 on 2023-03-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customer_card_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='frontend/src/productimages'),
        ),
    ]
